xml_dictionary = {
    'airplane-plane-AirPlane-0-1-2.xml': 'airplane-plane-AirPlane-0-1-2.xml',
    'bus-bus-ChicagoBusRoute1-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=1',
	'bus-bus-ChicagoBusRoute2-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=2',
	'bus-bus-ChicagoBusRoute3-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=3',
	'bus-bus-ChicagoBusRoute4-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=4',
	'bus-bus-ChicagoBusRoute5-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=5',
	'bus-bus-ChicagoBusRoute6-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=6',
	'bus-bus-ChicagoBusRoute7-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=7',
	'bus-bus-ChicagoBusRoute8-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=8',
	'bus-bus-ChicagoBusRoute9-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=9',
	'bus-bus-ChicagoBusRoute10-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=10',
	'bus-bus-ChicagoBusRoute11-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=11',
	'bus-bus-ChicagoBusRoute12-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=12',
	'bus-bus-ChicagoBusRoute14-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=14',
	'bus-bus-ChicagoBusRoute15-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=15',
	'bus-bus-ChicagoBusRoute18-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=18',
	'bus-bus-ChicagoBusRoute19-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=19',
	'bus-bus-ChicagoBusRoute20-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=20',
	'bus-bus-ChicagoBusRoute21-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=21',
	'bus-bus-ChicagoBusRoute22-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=22',
	'bus-bus-ChicagoBusRoute24-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=24',
	'bus-bus-ChicagoBusRoute26-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=26',
	'bus-bus-ChicagoBusRoute28-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=28',
	'bus-bus-ChicagoBusRoute29-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=29',
	'bus-bus-ChicagoBusRoute30-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=30',
	'bus-bus-ChicagoBusRoute31-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=31',
	'bus-bus-ChicagoBusRoute34-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=34',
	'bus-bus-ChicagoBusRoute35-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=35',
	'bus-bus-ChicagoBusRoute36-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=36',
	'bus-bus-ChicagoBusRoute37-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=37',
	'bus-bus-ChicagoBusRoute39-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=39',
	'bus-bus-ChicagoBusRoute43-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=43',
	'bus-bus-ChicagoBusRoute44-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=44',
	'bus-bus-ChicagoBusRoute47-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=47',
	'bus-bus-ChicagoBusRoute48-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=48',
	'bus-bus-ChicagoBusRoute49-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=49',
	'bus-bus-ChicagoBusRoute50-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=50',
	'bus-bus-ChicagoBusRoute51-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=51',
	'bus-bus-ChicagoBusRoute52-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=52',
	'bus-bus-ChicagoBusRoute53-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=53',
	'bus-bus-ChicagoBusRoute54-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=54',
	'bus-bus-ChicagoBusRoute55-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=55',
	'bus-bus-ChicagoBusRoute56-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=56',
	'bus-bus-ChicagoBusRoute57-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=57',
	'bus-bus-ChicagoBusRoute59-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=59',
	'bus-bus-ChicagoBusRoute60-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=60',
	'bus-bus-ChicagoBusRoute62-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=62',
	'bus-bus-ChicagoBusRoute63-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=63',
	'bus-bus-ChicagoBusRoute65-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=65',
	'bus-bus-ChicagoBusRoute66-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=66',
	'bus-bus-ChicagoBusRoute67-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=67',
	'bus-bus-ChicagoBusRoute68-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=68',
	'bus-bus-ChicagoBusRoute70-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=70',
	'bus-bus-ChicagoBusRoute71-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=71',
	'bus-bus-ChicagoBusRoute72-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=72',
	'bus-bus-ChicagoBusRoute73-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=73',
	'bus-bus-ChicagoBusRoute74-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=74',
	'bus-bus-ChicagoBusRoute75-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=75',
	'bus-bus-ChicagoBusRoute76-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=76',
	'bus-bus-ChicagoBusRoute77-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=77',
	'bus-bus-ChicagoBusRoute78-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=78',
	'bus-bus-ChicagoBusRoute79-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=79',
	'bus-bus-ChicagoBusRoute80-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=80',
	'bus-bus-ChicagoBusRoute81-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=81',
	'bus-bus-ChicagoBusRoute82-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=82',
	'bus-bus-ChicagoBusRoute84-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=84',
	'bus-bus-ChicagoBusRoute85-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=85',
	'bus-bus-ChicagoBusRoute86-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=86',
	'bus-bus-ChicagoBusRoute87-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=87',
	'bus-bus-ChicagoBusRoute88-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=88',
	'bus-bus-ChicagoBusRoute90-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=90',
	'bus-bus-ChicagoBusRoute91-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=91',
	'bus-bus-ChicagoBusRoute92-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=92',
	'bus-bus-ChicagoBusRoute93-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=93',
	'bus-bus-ChicagoBusRoute94-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=94',
	'bus-bus-ChicagoBusRoute95-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=95',
	'bus-bus-ChicagoBusRoute96-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=96',
	'bus-bus-ChicagoBusRoute97-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=97',
	'bus-bus-ChicagoBusRoute98-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=98',
	'bus-bus-ChicagoBusRoute100-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=100',
	'bus-bus-ChicagoBusRoute103-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=103',
	'bus-bus-ChicagoBusRoute106-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=106',
	'bus-bus-ChicagoBusRoute108-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=108',
	'bus-bus-ChicagoBusRoute111-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=111',
	'bus-bus-ChicagoBusRoute112-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=112',
	'bus-bus-ChicagoBusRoute115-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=115',
	'bus-bus-ChicagoBusRoute119-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=119',
	'bus-bus-ChicagoBusRoute120-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=120',
	'bus-bus-ChicagoBusRoute121-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=121',
	'bus-bus-ChicagoBusRoute124-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=124',
	'bus-bus-ChicagoBusRoute125-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=125',
	'bus-bus-ChicagoBusRoute126-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=126',
	'bus-bus-ChicagoBusRoute130-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=130',
	'bus-bus-ChicagoBusRoute134-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=134',
	'bus-bus-ChicagoBusRoute135-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=135',
	'bus-bus-ChicagoBusRoute136-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=136',
	'bus-bus-ChicagoBusRoute143-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=143',
	'bus-bus-ChicagoBusRoute146-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=146',
	'bus-bus-ChicagoBusRoute147-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=147',
	'bus-bus-ChicagoBusRoute148-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=148',
	'bus-bus-ChicagoBusRoute151-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=151',
	'bus-bus-ChicagoBusRoute152-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=152',
	'bus-bus-ChicagoBusRoute155-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=155',
	'bus-bus-ChicagoBusRoute156-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=156',
	'bus-bus-ChicagoBusRoute157-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=157',
	'bus-bus-ChicagoBusRoute165-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=165',
	'bus-bus-ChicagoBusRoute169-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=169',
	'bus-bus-ChicagoBusRoute171-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=171',
	'bus-bus-ChicagoBusRoute172-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=172',
	'bus-bus-ChicagoBusRoute192-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=192',
	'bus-bus-ChicagoBusRoute201-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=201',
	'bus-bus-ChicagoBusRoute206-0-11-12.xml': 'http://ctabustracker.com/bustime/map/getBusesForRoute.jsp?route=206',
}

def get():
    # add realtime visualization to html

    map_name = ''
    realtime_data = open('templates/supervision.js', 'r').read()
    # find map name
    read_index = open('templates/index.html', 'r').readlines()

    file_names = [key for key, value in xml_dictionary.items()]

    with open('templates/index.html', 'w') as index:
        for line in range(len(read_index) - 1):
            if read_index[line].strip().endswith('L.map('):
                map_name = read_index[line].strip(' ').replace('\t', '').replace('var ','').replace(' = L.map(','').replace('\n','')

                realtime_data = realtime_data.replace('MAP', map_name).replace('ARRAY',str(file_names))

            index.write(read_index[line])
        index.write(realtime_data.replace('MAP', map_name))
        index.write('\n</script>')